Repository oceanprotocol/keeper-contracts, pull requests merged in 2018-11, with the labels that each got.

#153 Adding artifacts for different networks
  .travis.yml
  package.json
  setup.py
  truffle.js
Labels: status:wip

#162 remove redundent code from SLA contract
  contracts/SLA/ServiceAgreement.sol
  package-lock.json
Labels: enhancement, security

#165 Feature/java package
  .bumpversion.cfg
  .maven.xml
  .travis.yml
  package.json
  pom.xml
  scripts/maven.sh
  setup.cfg
  setup.py
Labels: devops

#166 fix templateId
  contracts/SLA/ServiceAgreement.sol
  test/ServiceAgreement.Test.js
Labels: trilobite
