Repository oceanprotocol/keeper-contracts, pull requests merged in 2019-01, with the labels that each got.

#218 revert breaking change in executeAgreement
  contracts/SLA/ServiceAgreement.sol
  test/unit/ServiceAgreement.Test.js
Labels: Integration

#244 Feature/dispenser
  contracts/Dispenser.sol
  contracts/OceanMarket.sol
  contracts/OceanToken.sol
  migrations/100_register_minters.js
  migrations/12_deploy_payments.js
  migrations/13_deploy_access.js
  migrations/14_deploy_compute.js
  migrations/15_deploy_fitchain.js
  migrations/7_deploy_dispenser.js
  migrations/7_deploy_market.js
  package-lock.json
  test/int/ComputeConditions.Test.js
  test/int/FitchainConditions.Test.js
  test/int/PaymentConditions.Test.js
  test/int/ServiceExecutionAgreement/ServiceExecutionAgreement.Test.js
  test/unit/Dispenser/Dispenser.Test.js
  test/unit/Dispenser/requestTokens.Test.js
  test/unit/OceanToken/setReceiver.js
  test/unit/OceanToken/transfer.js
  test/unit/OceanToken/transferFrom.js
  test/unit/SEA/PaymentConditions/lockPayment.Test.js
  test/unit/SEA/PaymentConditions/refundPayment.Test.js
Labels: enhancement, refactor, tethys

#232 fix code coverage again
  package-lock.json
  package.json
Labels: devops, enhancement, refactor

#253 Add release instructions
  README.md
  RELEASE_PROCESS.md
Labels: devops, enhancement

#227 [WIP] Security Reports
  .gitignore
  .travis.yml
  .travis/travis_keeper-contracts-security-reports.enc
  contracts/SEA/FitchainConditions.sol
  mythril-report.md
  package-lock.json
  package.json
  requirements_dev.txt
Labels: security

#276 Changing artifacts UID and GID
  scripts/keeper.sh
Labels: devops

#282 Fix several deployment problems
  Dockerfile
  doc/upgrades.md
  package.json
  scripts/deployContracts.js
  scripts/deployContracts.sh
  scripts/exportArtifacts.js
  scripts/keeper.sh
  scripts/parity.sh
  scripts/setupWallet.js
  scripts/setupWalletWrapper.js
  test/helpers/ZeppelinHelper.js
  test/helpers/utils.js
  truffle.js
Labels: v0.6

#291 V0.6.10
  .bumpversion.cfg
  README.md
  artifacts/AccessConditions.kovan.json
  artifacts/AccessConditions.nile.json
  artifacts/ComputeConditions.kovan.json
  artifacts/ComputeConditions.nile.json
  artifacts/DIDRegistry.kovan.json
  artifacts/DIDRegistry.nile.json
  artifacts/Dispenser.kovan.json
  artifacts/Dispenser.nile.json
  artifacts/FitchainConditions.kovan.json
  artifacts/FitchainConditions.nile.json
  artifacts/OceanToken.kovan.json
  artifacts/OceanToken.nile.json
  artifacts/PaymentConditions.kovan.json
  artifacts/PaymentConditions.nile.json
  artifacts/ServiceExecutionAgreement.kovan.json
  artifacts/ServiceExecutionAgreement.nile.json
  package-lock.json
  package.json
  pom.xml
  setup.cfg
  setup.py
  truffle.js
Labels: v0.6

#286 first and initial version of auto generated contract documentation
  doc/contracts/AccessConditions.md
  doc/contracts/ComputeConditions.md
  doc/contracts/DIDRegistry.md
  doc/contracts/Dispenser.md
  doc/contracts/FitchainConditions.md
  doc/contracts/OceanToken.md
  doc/contracts/PaymentConditions.md
  doc/contracts/ServiceExecutionAgreement.md
  scripts/contracts/doc-generator.js
  scripts/contracts/report.js
Labels: v0.7

#285 fix/security-threats-reported-by-Mythril
  contracts/DIDRegistry.sol
  contracts/MultiSigWallet.sol
  contracts/OceanToken.sol
  contracts/SEA/Common.sol
  contracts/SEA/FitchainConditions.sol
  contracts/testContracts/DIDRegistry/DIDRegistryChangeFunctionSignature.sol
  contracts/testContracts/DIDRegistry/DIDRegistryChangeInStorageAndLogic.sol
  contracts/testContracts/DIDRegistry/DIDRegistryWithBug.sol
  package.json
  test/unit/DIDRegistry/DIDRegistry.Test.js
  test/unit/SEA/ComputeConditions/fulfillUpload.Test.js
  test/unit/SEA/ComputeConditions/submitAlgorithmHash.Test.js
  test/unit/SEA/ComputeConditions/submitHashSignature.Test.js
  test/unit/SEA/ServiceExecutionAgreement/Agreement/initializeAgreement.Test.js
  test/upgradability/DIDRegistry/DIDRegistryChangeFunctionSignature.Test.js
  test/upgradability/DIDRegistry/DIDRegistryChangeInStorageAndLogic.Test.js
  test/upgradability/DIDRegistry/DIDRegistryWithBug.Test.js
Labels: v0.7

#313 Example of unit test cleanup
  v0.7/package.json
  v0.7/test/unit/storage/ConditionStoreManager.Test.js
Labels: v0.7
